POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impvc2h5ZWUxMjMiLCJpZCI6IjYyNWYzZmUzODAwYzllODJkMjc0MGEwNyIsImlhdCI6MTY1MDQwOTQ2Mn0.hecdvFicTcbkGNv4YsNm6k2pefm-BdAHOQJWo-jhy5k

{
    "content": "wow this actually works",
    "important": true
}